title: <p align="center"> Dharmi Gala </p>
logo: assets/Circle Picture.jpg
description:
  <p align="center">
  <a href="assets/DharmiGala Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/dharmigala/">LinkedIn</a>

  </p>
  
  <p align="justify">
  Data Scientist with proven experience delivering production-grade, data-backed solutions across healthcare, real estate, and pharmaceutical domains. 
  <br>
  Skilled in Python, SQL, ML frameworks, and cloud technologies (AWS, GCP, Kubernetes) with expertise in translating complex business problems into scalable, data-driven solutions.
  <br><br>
  I currently work at Jones Lang LaSalle as a Business Analyst with a focus on Business intelligence solutions.
  <br><br>
  </p>
  

theme: jekyll-theme-minimal
