title: <p align="center"> Dharmi Gala </p>
logo: assets/Circle Picture.jpg
description:
  <p align="center">
  <a href="assets/DharmiGala Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/dharmigala/">LinkedIn</a>

  </p>
  
  <p align="justify">
  Data Scientist with proven experience delivering production-grade, data-backed solutions across healthcare, real estate, and pharmaceutical domains. 
  <br><br>
  </p>
  

theme: jekyll-theme-minimal
